//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCSDL_QuanLyShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPN
    {
        public int IDCTPN { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public int IDSP { get; set; }
        public int IDPN { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
        public object TenPN { get; internal set; }
    }
}
